general:
  masterVolume: 100
  musicMasterVolume: 100
  fxMasterVolume: 60

listener:
  updatePosition: true
  updateRotation: false
  basePositionX: 720
  basePositionY: 450
  baseRotation: -90

music:
  menuVolume: 80
  levelVolume: 70

fx:
  fireVolume: 100
  targetStartVolume: 60
  targetImpactVolume: 100
  wallImpactVolume: 90
  projectileVolume: 55
  motorMaximumVolume: 20
  daySwitchVolume: 70