general:
  masterVolume: 100
  musicMasterVolume: 100
  fxMasterVolume: 100

listener:
  updatePosition: true
  updateRotation: false
  basePositionX: 720
  basePositionY: 450
  baseRotation: -90

music:
  menuVolume: 100
  levelVolume: 80

fx:
  fireVolume: 100
  targetStartVolume: 80
  targetImpactVolume: 80
  targetCatchVolume: 70
  wallImpactVolume: 70
  projectileVolume: 25
  motorMaximumVolume: 10
  daySwitchVolume: 50