general:
  masterVolume: 80
  musicMasterVolume: 80
  fxMasterVolume: 80

listener:
  updatePosition: true
  updateRotation: true
  basePositionX: 720
  basePositionY: 450
  baseRotation: -90

music:
  menuVolume: 50
  levelVolume: 80

fx:
  fireVolume: 100
  targetStartVolume: 60
  targetImpactVolume: 100
  wallImpactVolume: 90
  projectileVolume: 70
  motorMaximumVolume: 15